analyze:
    async: true
    create-group: true
    solc: 0.5.16
    check-properties: true
    remappings:
    targets:
        - contracts/VerifyUniswapV2Pair.sol:VerifyUniswapV2Pair
        - contracts/VerifyUniswapV2ERC20.sol:VerifyUniswapV2ERC20
